name: reviewers_community
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage:
  http: 0.13.4
  google_fonts: 2.2.0
  material_design_icons_flutter: 5.0.6595
  google_maps_flutter: 2.1.1
  shared_preferences: ^2.0.5
  flutter_feather_icons: ^2.0.0+1
  url_launcher: ^6.0.3
  flutter: 
    sdk: flutter
  flutx:
    path: ../flutx

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/place_holder.png
    - assets/images/

